name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Get current Git tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Replace image
        uses: mikefarah/yq@v4.9.3
        with:
          cmd: yq eval -i '.spec.template.spec.containers[0].image = "my-app:${{steps.tag.outputs.tag}}"' deployment.yaml
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update deployment manifest"
          branch: master
          file_pattern: deployment.yaml
